import type { Metadata } from "next";
import {
  Festive,
  League_Script,
  Nunito_Sans,
  Raleway,
  Story_Script,
} from "next/font/google";
import "./globals.css";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

const storyScript = Story_Script({
  variable: "--font-story-script",
  subsets: ["latin"],
  weight: ["400"],
});

const festive = Festive({
  variable: "--font-festive",
  subsets: ["latin"],
  weight: ["400"],
});

const leagueScript = League_Script({
  variable: "--font-league-script",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} ${nunitoSans.variable} ${storyScript.variable} ${festive.variable} ${leagueScript.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
